src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnimalRepository::class)
 */
class Animal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     * @Groups("api_animals_list")
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     */
    private $picture;

    /**
     * @ORM\Column(type="integer")
     * @Groups("api_animals_list")
     */
    private $age;

    /**
     * @ORM\Column(type="boolean")
     * @Groups("api_animals_list")
     */
    private $child_compatibility;

    /**
     * @ORM\Column(type="boolean")
     * @Groups("api_animals_list")
     */
    private $other_animal_compatibility;

    /**
     * @ORM\Column(type="boolean")
     * @Groups("api_animals_list")
     */
    private $garden_needed;

    /**
     * @ORM\Column(type="smallint")
     * @Groups("api_animals_list")
     */
    private $status;

    /**
     * @ORM\Column(type="text")
     * @Groups("api_animals_list")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=Department::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("api_animals_list")
     */
    private $department;

    /**
     * @ORM\ManyToOne(targetEntity=Species::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("api_animals_list")
     */
    private $species;

    /**
     * @ORM\ManyToOne(targetEntity=Association::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("api_animals_list")
     */
    private $association;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getChildCompatibility(): ?bool
    {
        return $this->child_compatibility;
    }

    public function setChildCompatibility(bool $child_compatibility): self
    {
        $this->child_compatibility = $child_compatibility;

        return $this;
    }

    public function getOtherAnimalCompatibility(): ?bool
    {
        return $this->other_animal_compatibility;
    }

    public function setOtherAnimalCompatibility(bool $other_animal_compatibility): self
    {
        $this->other_animal_compatibility = $other_animal_compatibility;

        return $this;
    }

    public function getGardenNeeded(): ?bool
    {
        return $this->garden_needed;
    }

    public function setGardenNeeded(bool $garden_needed): self
    {
        $this->garden_needed = $garden_needed;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getSpecies(): ?Species
    {
        return $this->species;
    }

    public function setSpecies(?Species $species): self
    {
        $this->species = $species;

        return $this;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): self
    {
        $this->association = $association;

        return $this;
    }
}

src/Controller/Api/AnimalController.php
<?php

namespace App\Controller\Api;

use App\Entity\Animal;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Serializer\Exception\NotEncodableValueException;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;
use Symfony\Component\Serializer\Serializer;

class AnimalController extends AbstractController
{
    /**
     * @Route("/api/animal/form", name="app_api_animal", methods={"POST","GET"})
     */
    public function getResults(Request $request, SerializerInterface $serializer, AnimalRepository $animalRepository, ValidatorInterface $validator, ManagerRegistry $doctrine): Response
    {

        // Récupérer le contenu JSON
        $jsonContent = $request->getContent();
    
        $parsed_json = json_decode($jsonContent);
        dump($parsed_json);

        // Mettre les critères du Json en variables php
        // Todo - Gérer la validations des données
        
        $gender = $parsed_json->gender;   
        if ($gender === 0) {
            $genderMin = 0;
            $genderMax = 0;
        }
        if ($gender === 1) {
            $genderMin = 1;
            $genderMax = 1;
        }
        if ($gender === 2) {
            $genderMin = 0;
            $genderMax = 1;
        }
        
        $species = $parsed_json->species; 
// Todo vérouiller le choix des ages
        $age = $parsed_json->age;    
        if ($age === 0) {
            $ageMin = 0;
            $ageMax = 1;
        }
        if ($age === 1) {
            $ageMin = 1;
            $ageMax = 5;
        }
        if ($age === 2) {
            $ageMin = 6;
            $ageMax = 10;
        }
        if ($age === 3) {
            $ageMin = 11;
            $ageMax = 30;
        }  
        if ($age === 4) {
            $ageMin = 0;
            $ageMax = 30;
        }
        
        $child_compatibility = $parsed_json->childCompatibility;    
        $other_animal_compatibility = $parsed_json->other_animal_compatibility;    
        $garden_needed = $parsed_json->garden_needed;
        $status = $parsed_json->status;

        $department = $parsed_json->department; 
        
        // Envoyer les variables dans une méthode qui executera la requete SQL et les stocker dans une variable
        $results = $animalRepository->findAnimalsFromSearchForm($genderMin, $genderMax,$species, $ageMin, $ageMax, $child_compatibility, $other_animal_compatibility, $garden_needed, $status, $department);
       
        // Envoyer la variable contenant les résultats en json pour le Front
        return $this->json($results, Response::HTTP_OK,[], ['groups' => 'api_animals_list']);

    }

    /**
     * @Route("/api/animal", name="app_api_animal_list", methods={"GET"})
     */
    public function animalList(AnimalRepository $animalRepository): Response
    {
        $animals = $animalRepository->findAll();
        //dump($animals);

        return $this->json($animals, Response::HTTP_OK,[],['groups' => 'api_animals_list']);
    }

    /**
     * @Route("/api/animal/caroussel", name="app_api_animal_caroussel", methods={"GET"})
     */
    public function animalCaroussel(AnimalRepository $animalRepository): Response
    {
        // $animalIdMin = $animalRepository->findItemsMin();
        // $animalIdMax = $animalRepository->findItemsMax();
        // // dump($animalIdMin);
        // dd($animalIdMax);



        $animalsCount = $animalRepository->findAnimalsForCaroussel();

        $keys = array_rand($animalsCount,10);

        $results = [];
        foreach ($keys as $key) {
            $results[] = $animalsCount[$key];
        }

        return $this->json($results, Response::HTTP_OK);
    }
}





// public function findOneWithAllData($movieId): ?Movie
//     {
//         $entityManager = $this->getEntityManager();

//         $query = $entityManager->createQuery(
//             'SELECT m, g, c, p
//             FROM App\Entity\Movie m
//             JOIN m.genres g
//             JOIN m.castings c
//             JOIN c.person p
//             WHERE m.id = :id'
//         );
//         $query->setParameter('genre', $movieId);
//         $query->setParameter('enfant', $movieId);

//         // returns the movie or null if not found
//         return $query->getOneOrNullResult();
//     }

src/Controller/Back/AnimalController.php
<?php

namespace App\Controller\Back;

use App\Entity\Animal;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/animal")
 */
class AnimalController extends AbstractController
{
    /**
     * @Route("/", name="app_animal_index", methods={"GET"})
     */
    public function index(AnimalRepository $animalRepository): Response
    {
        return $this->render('back/animal/index.html.twig', [
            'animals' => $animalRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_animal_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AnimalRepository $animalRepository): Response
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/animal/new.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_show", methods={"GET"})
     */
    public function show(Animal $animal): Response
    {
        //dd($animal->getGardenNeeded());
        return $this->render('back/animal/show.html.twig', [
            'animal' => $animal,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_animal_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/animal/edit.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_delete", methods={"POST"})
     */
    public function delete(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$animal->getId(), $request->request->get('_token'))) {
            $animalRepository->remove($animal);
        }

        return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/AssociationController.php
<?php

namespace App\Controller\Back;

use App\Entity\Association;
use App\Form\AssociationType;
use App\Repository\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/association")
 */
class AssociationController extends AbstractController
{
    /**
     * @Route("/", name="app_association_index", methods={"GET"})
     */
    public function index(AssociationRepository $associationRepository): Response
    {
        return $this->render('back/association/index.html.twig', [
            'associations' => $associationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_association_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AssociationRepository $associationRepository): Response
    {
        $association = new Association();
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $associationRepository->add($association);
            return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/association/new.html.twig', [
            'association' => $association,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_association_show", methods={"GET"})
     */
    public function show(Association $association): Response
    {
        return $this->render('back/association/show.html.twig', [
            'association' => $association,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_association_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Association $association, AssociationRepository $associationRepository): Response
    {
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $associationRepository->add($association);
            return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/association/edit.html.twig', [
            'association' => $association,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_association_delete", methods={"POST"})
     */
    public function delete(Request $request, Association $association, AssociationRepository $associationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$association->getId(), $request->request->get('_token'))) {
            $associationRepository->remove($association);
        }

        return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back/animal/_delete_form.html.twig
<form method="post" action="{{ path('app_animal_delete', {'id': animal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ animal.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/back/animal/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/back/animal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Animal{% endblock %}

{% block body %}
<div class="container">
    <h1>Edition la fiche animal</h1>

    {{ include('back/animal/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('app_animal_index') }}">Retour à la liste des animaux</a>

    {{ include('back/animal/_delete_form.html.twig') }}

</div>
{% endblock %}

templates/back/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal index{% endblock %}

{% block body %}

<div class="container">
    <h1>Liste des animaux</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Genre</th>
                <th>Photo</th>
                <th>Age</th>
                <th>Sociable avec les enfants ?</th>
                <th>Sociable avec autres animaux ?</th>
                <th>Besoin d'un jardin ?</th>
                <th>Status</th>
                <th>Description</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for animal in animals %}
            <tr>
                <td>{{ animal.id }}</td>
                <td>{{ animal.name }}</td>
                <td>{% if animal.gender == '0' %} Femelle{% elseif animal.gender == '1' %} Male{% endif %}</td>
                <td><img class="img_backoffice_index" src="{{ animal.picture }}"></td>
                <td>{{ animal.age }}</td>
                <td>{{ animal.childCompatibility ? 'Oui' : 'Non' }}</td>
                <td>{{ animal.otherAnimalCompatibility ? 'Oui' : 'Non' }}</td>
                <td>{{ animal.gardenNeeded ? 'Oui' : 'Non' }}</td>
                <td>{% if animal.status == '0' %} Disponible{% elseif animal.status == '1' %} Resa en cours{% elseif animal.status == '2' %} Indisponible{% elseif animal.status == '3' %} Adopté{% endif %}</td>
                <td>{{ animal.description }}</td>
                <td>
                    <a href="{{ path('app_animal_show', {'id': animal.id}) }}">Voir plus</a>
                    <a href="{{ path('app_animal_edit', {'id': animal.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_animal_new') }}">Ajouter</a>
    </div>
{% endblock %}

templates/back/animal/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Animal{% endblock %}

{% block body %}
<div class="container">
    <h1>Ajout d'un animal</h1>

    {{ include('back/animal/_form.html.twig') }}

    <a href="{{ path('app_animal_index') }}">Retour à la liste des animaux</a>
</div>
{% endblock %}

templates/back/animal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
<div class="container">
    <h1>Fiche de l'animal</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ animal.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ animal.name }}</td>
            </tr>
            <tr>
                <th>Espèce animale</th>
                <td>{{ animal.species.name }}</td>
            </tr>
            <tr>
                <th>Genre</th>
                <td>{% if animal.gender == '0' %} Femelle{% elseif animal.gender == '1' %} Male{% endif %}</td>
                <td><img class="img_backoffice_index" src="{{ animal.picture }}"></td>
            </tr>
            <tr>
                <th>Photo</th>
                <td><img class="img_backoffice_show" src="{{ animal.picture }}"></td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ animal.age }}</td>
            </tr>
            <tr>
                <th>Sociable avec les enfants ?</th>
                <td>{{ animal.childCompatibility ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>Sociable avec autres animaux ?</th>
                <td>{{ animal.otherAnimalCompatibility ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th>Besoin d'un jardin ?</th>
                <td>{{ animal.gardenNeeded ? 'Oui' : 'Non'}}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{% if animal.status == '0' %} Disponible{% elseif animal.status == '1' %} Resa en cours{% elseif animal.status == '2' %} Indisponible{% elseif animal.status == '3' %} Adopté{% endif %}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ animal.description }}</td>
            </tr>
                        <tr>
                <th>Association</th>
                <td>{{ animal.association.name }}</td>
            </tr>
                        <tr>
                <th>Département d'accueil</th>
                <td>{{ animal.department.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_animal_index') }}">Retour à la liste</a>

    <a href="{{ path('app_animal_edit', {'id': animal.id}) }}">Mettre à jour</a>

    {{ include('back/animal/_delete_form.html.twig') }}
    </div>
{% endblock %}