src/Entity/Association.php
<?php

namespace App\Entity;

use App\Repository\AssociationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Serializer\Annotation\Groups;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AssociationRepository::class)
 */
class Association
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Groups("api_associations_list")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     */
    private $siren;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("api_animals_list")
     * @Groups("api_associations_list")
     */
    private $email;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity=Animal::class, mappedBy="association")
     */
    private $animals;

    public function __construct()
    {
        $this->animals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSiren(): ?string
    {
        return $this->siren;
    }

    public function setSiren(string $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return Collection<int, Animal>
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    public function addAnimal(Animal $animal): self
    {
        if (!$this->animals->contains($animal)) {
            $this->animals[] = $animal;
            $animal->setAssociation($this);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): self
    {
        if ($this->animals->removeElement($animal)) {
            // set the owning side to null (unless already changed)
            if ($animal->getAssociation() === $this) {
                $animal->setAssociation(null);
            }
        }

        return $this;
    }
}

src/Controller/Api/AssociationController.php
<?php

namespace App\Controller\Api;

use App\Repository\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AssociationController extends AbstractController
{
    /**
     * @Route("/api/association", name="app_api_association")
     */
    public function associationList(AssociationRepository $associationRepository): Response
    {
        $associations = $associationRepository->findAll();

        return $this->json($associations, Response::HTTP_OK,[], ['groups' => 'api_associations_list']);
    }
}

src/Controller/Back/AnimalController.php
<?php

namespace App\Controller\Back;

use App\Entity\Animal;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/animal")
 */
class AnimalController extends AbstractController
{
    /**
     * @Route("/", name="app_animal_index", methods={"GET"})
     */
    public function index(AnimalRepository $animalRepository): Response
    {
        return $this->render('back/animal/index.html.twig', [
            'animals' => $animalRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_animal_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AnimalRepository $animalRepository): Response
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/animal/new.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_show", methods={"GET"})
     */
    public function show(Animal $animal): Response
    {
        //dd($animal->getGardenNeeded());
        return $this->render('back/animal/show.html.twig', [
            'animal' => $animal,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_animal_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $animalRepository->add($animal);
            return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/animal/edit.html.twig', [
            'animal' => $animal,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_animal_delete", methods={"POST"})
     */
    public function delete(Request $request, Animal $animal, AnimalRepository $animalRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$animal->getId(), $request->request->get('_token'))) {
            $animalRepository->remove($animal);
        }

        return $this->redirectToRoute('app_animal_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/AssociationController.php
<?php

namespace App\Controller\Back;

use App\Entity\Association;
use App\Form\AssociationType;
use App\Repository\AssociationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/association")
 */
class AssociationController extends AbstractController
{
    /**
     * @Route("/", name="app_association_index", methods={"GET"})
     */
    public function index(AssociationRepository $associationRepository): Response
    {
        return $this->render('back/association/index.html.twig', [
            'associations' => $associationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_association_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AssociationRepository $associationRepository): Response
    {
        $association = new Association();
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $associationRepository->add($association);
            return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/association/new.html.twig', [
            'association' => $association,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_association_show", methods={"GET"})
     */
    public function show(Association $association): Response
    {
        return $this->render('back/association/show.html.twig', [
            'association' => $association,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_association_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Association $association, AssociationRepository $associationRepository): Response
    {
        $form = $this->createForm(AssociationType::class, $association);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $associationRepository->add($association);
            return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/association/edit.html.twig', [
            'association' => $association,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_association_delete", methods={"POST"})
     */
    public function delete(Request $request, Association $association, AssociationRepository $associationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$association->getId(), $request->request->get('_token'))) {
            $associationRepository->remove($association);
        }

        return $this->redirectToRoute('app_association_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/SpeciesController.php
<?php

namespace App\Controller\Back;

use App\Entity\Species;
use App\Form\SpeciesType;
use App\Repository\SpeciesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/species")
 */
class SpeciesController extends AbstractController
{
    /**
     * @Route("/", name="app_species_index", methods={"GET"})
     */
    public function index(SpeciesRepository $speciesRepository): Response
    {
        return $this->render('back/species/index.html.twig', [
            'species' => $speciesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_species_new", methods={"GET", "POST"})
     */
    public function new(Request $request, SpeciesRepository $speciesRepository): Response
    {
        $species = new Species();
        $form = $this->createForm(SpeciesType::class, $species);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $speciesRepository->add($species);
            return $this->redirectToRoute('app_species_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/species/new.html.twig', [
            'species' => $species,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_species_show", methods={"GET"})
     */
    public function show(Species $species): Response
    {
        return $this->render('back/species/show.html.twig', [
            'species' => $species,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_species_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Species $species, SpeciesRepository $speciesRepository): Response
    {
        $form = $this->createForm(SpeciesType::class, $species);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $speciesRepository->add($species);
            return $this->redirectToRoute('app_species_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/species/edit.html.twig', [
            'species' => $species,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_species_delete", methods={"POST"})
     */
    public function delete(Request $request, Species $species, SpeciesRepository $speciesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$species->getId(), $request->request->get('_token'))) {
            $speciesRepository->remove($species);
        }

        return $this->redirectToRoute('app_species_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Back/UserController.php
<?php

namespace App\Controller\Back;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="app_back_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('back/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_back_user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);
            return $this->redirectToRoute('app_back_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('back/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_back_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);
            return $this->redirectToRoute('app_back_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('back/user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_back_user_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user);
        }

        return $this->redirectToRoute('app_back_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/back/association/_delete_form.html.twig
<form method="post" action="{{ path('app_association_delete', {'id': association.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ association.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/back/association/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/back/association/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer la fiche de l'Association{% endblock %}

{% block body %}
<div class="container">
    <h1>Editer la fiche de l'Association</h1>

    {{ include('back/association/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_association_index') }}">Retour à la liste des associations</a>

    {{ include('back/association/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/back/association/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Associations{% endblock %}

{% block body %}
<div class="container">
    <h1>Liste des Associations</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Siren</th>
                <th>Adresse</th>
                <th>Code postal</th>
                <th>Ville</th>
                <th>Numéro de téléphone</th>
                <th>Email</th>
                <th>Statut</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for association in associations %}
            <tr>
                <td>{{ association.id }}</td>
                <td>{{ association.name }}</td>
                <td>{{ association.description }}</td>
                <td>{{ association.siren }}</td>
                <td>{{ association.street }}</td>
                <td>{{ association.zipCode }}</td>
                <td>{{ association.city }}</td>
                <td>{{ association.phoneNumber }}</td>
                <td>{{ association.email }}</td>
                <td>{{ association.active ? 'Actif' : 'Inactif' }}</td>
                <td>
                    <a href="{{ path('app_association_show', {'id': association.id}) }}">Voir plus</a>
                    <a href="{{ path('app_association_edit', {'id': association.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_association_new') }}">Ajouter</a>
    </div>
{% endblock %}

templates/back/association/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Association{% endblock %}

{% block body %}
<div class="container">
    <h1>Ajout d'une association</h1>

    {{ include('back/association/_form.html.twig') }}

    <a href="{{ path('app_association_index') }}">Retour à la liste des associations</a>
</div>
{% endblock %}

templates/back/association/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association{% endblock %}

{% block body %}
<div class="container">
    <h1>Association</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ association.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ association.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ association.description }}</td>
            </tr>
            <tr>
                <th>Siren</th>
                <td>{{ association.siren }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ association.street }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ association.zipCode }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ association.city }}</td>
            </tr>
            <tr>
                <th>Numéro de téléphone</th>
                <td>{{ association.phoneNumber }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ association.email }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ association.active ? 'Actif' : 'Inactif'  }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_association_index') }}">Retour à la liste</a>

    <a href="{{ path('app_association_edit', {'id': association.id}) }}">Mettre à jour</a>

    {{ include('back/association/_delete_form.html.twig') }}
    </div>
{% endblock %}